version: '2'

services:
  database-dev:
    build: ./mysql
    ports:
      - "3308:3308"
    environment:
      MYSQL_DATABASE: devsummit
      MYSQL_USER: root
      MYSQL_PASSWORD: GAKtahu
      MYSQL_ROOT_PASSWORD: GAKtahu

  web-dev:
    depends_on:
      - database-dev
    build: .
    container_name: devsummit-dev
    ports:
      - "8081:8081"
    volumes:
      - .:/backend
